### ISSUE TITLE
new badges

### ISSUE THREAD

**Issue by GregorDeCillia** [GuangchuangYu/badger#2]
I really like the idea of this package and would like to contribute a couple of new badges. Are you, @GuangchuangYu, willing to review a PR for the following badges?

* GitHub last commit: [example](https://img.shields.io/github/last-commit/GuangchuangYu/badger.svg)
* GitHub code size [example](https://img.shields.io/github/languages/code-size/GuangchuangYu/badger.svg)
* CRAN version: [example](https://www.r-pkg.org/badges/version/badger)
* CRAN downloads: [example](http://cranlogs.r-pkg.org/badges/badger)
* travis build-status: [example](https://api.travis-ci.org/rstudio/markdown.svg?branch=master)
* coveralls coverage status: [example](https://coveralls.io/repos/github/statistikat/simPop/badge.svg?branch=master)
* lifecycle: [example](https://img.shields.io/badge/lifecycle-maturing-blue.svg)

**Comment by GuangchuangYu** [comment]
of course, PR is welcome.
