### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by wleoncio** [GuangchuangYu/badger#28]
This package doesn't seem to contain a testing framework, so new code contributions are at risk of inadvertently breaking something. I, for one, really enjoy using the [testthat](https://cran.r-project.org/web/packages/testthat/) package for that. If I have some spare time in the near future, I could help you set this up (or improve it, if someone else gets around to it faster).

**Comment by GuangchuangYu** [comment]
Thanks @wleoncio ! I am glad to see it happen.
