### ISSUE TITLE
Wrong URL returned by `currentGitHubRef ` in case of multiple github URL 

### ISSUE THREAD

**Issue by DDorch** [GuangchuangYu/badger#35]
URL packages usually combines github.com and github.io urls like for this one: https://github.com/cran/ropenblas/blob/dd74d5b3f23a57c63a3b2520d3dc81f1f9554bdf/DESCRIPTION#L15

In that case, the URL returned by `currentGitHubRef ` is wrong:

```
> badger::badge_devel(color = "blue")
[1] "[![](https://img.shields.io/badge/devel%20version-0.2.6-blue.svg)](https://github.com/https://ddorch.github.io/Rthingsboard/)"
```

**Comment by GuangchuangYu** [comment]
fixed in v0.2.0
