### ISSUE TITLE
Version 0.2.0 + CRAN release?

### ISSUE THREAD

**Issue by wleoncio** [GuangchuangYu/badger#39]
Considering the new feature brought by PR #37, I was wondering if a bump to version 0.2.0 and a CRAN release are under consideration. I've been using `badge_repostatus()` a lot, and having this available on CRAN instead of GitHub only would ease and potentially increase use of this tool and standard.

**Comment by GuangchuangYu** [comment]
thanks @wleoncio and the v0.2.0 is on CRAN now.
