### ISSUE TITLE
codecov domain name update

### ISSUE THREAD

**Issue by bschilder** [GuangchuangYu/badger#40]
hi @GuangchuangYu , 

I noticed recently that when when running `R CMD check` with the `--as-cran` flag, it gives a warning that the code cov URL has been changed slightly.  This comes up because I have `badger::badge_codecov()` in my *README.Rmd* file.

In the case of my package [MAGMA_Celltyping](https://github.com/neurogenomics/MAGMA_Celltyping), this shows up as:
  
```
 URL: https://codecov.io/gh/neurogenomics/MAGMA_Celltyping (moved to https://app.codecov.io/gh/neurogenomics/MAGMA_Celltyping)
    From: README.md
    Status: 200
    Message: OK
```

The old URL forwards to the new one just fine, but for the sake of CRAN checks would it be possible to use the new domain name in `badger::badge_codecov()`?

Many thanks, 
Brian

**Comment by GuangchuangYu** [comment]
already updated, see <https://github.com/GuangchuangYu/badger/pull/33>, and will soon update the CRAN version.

**Comment by bschilder** [comment]
Great, thanks!
